spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create-drop
#    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: true
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated