spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create-drop
#    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: true
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  security:
    oauth2:
      client:
        kakao:
          clientId: id
          clientSecret: key
          authorizationGrantType: authorization_code
          redirectUri: "{baseUrl}/login/oauth2/code/kakao"
          clientAuthenticationMethod: POST
      provider:
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttributeName: id